FROM debian

RUN apt-get update && \
    apt-get install -y openssh-server patch rssh && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /root


# PATCHING configuration
COPY ssh_keys/ssh_host_rsa_key /etc/ssh/ssh_host_rsa_key
COPY patches/*.patch  dockersetup/

RUN cd /etc/ssh  && patch < /root/dockersetup/sshd_config.patch && \
    cd /etc      && patch < /root/dockersetup/rssh.conf.patch


# Setting up environment
RUN mkdir /run/sshd
RUN useradd deploy -s /usr/bin/rssh
COPY ssh_keys/authorized_keys /home/deploy/.ssh/authorized_keys
RUN mkdir /home/deploy/deploy && \
    touch /home/deploy/deploy/.keepperm && \
    chmod -R 440 /home/deploy && \
    chmod 550 /home/deploy /home/deploy/.ssh && \
    chmod 400 /home/deploy/.ssh/authorized_keys && \
    chmod 775 /home/deploy/deploy && \
    chown -R deploy:deploy /home/deploy


CMD ["/usr/sbin/sshd", "-D"]
